LINCUBE_HOME=/s3i/Net-Protect
LINCUBE_BASE=$LINCUBE_HOME/www/WEB-INF
LINCUBE_LIBRARY=$LINCUBE_BASE/lib
HOME_DIR=/s3i/Net-Protect/www/extModule
JAVA_PATH=/s3i/Net-Protect/java/bin/java

export LINCUBE_HOME LINCUBE_BASE HOME_DIR JAVA_PATH

CLASSPATH=.:$LINCUBE_BASE/conf:$LINCUBE_BASE/classes
CLASSPATH=$CLASSPATH:$LINCUBE_LIBRARY/commons-logging-1.1.1.jar:$LINCUBE_LIBRARY/log4j-1.2.16.jar
CLASSPATH=$CLASSPATH:$LINCUBE_LIBRARY/slf4j-api-1.7.5.jar
CLASSPATH=$CLASSPATH:$LINCUBE_LIBRARY/slf4j-log4j12-1.7.5.jar

export CLASSPATH

LOGGING_CONFIG="-Dlog4j.configurationFile=$LINCUBE_BASE/log4j/log4j2_ole.xml"
export LOGGING_CONFIG

$JAVA_PATH -Dfile.encoding=UTF-8 -Xms1024m -Xmx2048m  $LIBRARY_CONFIG $LOGGING_CONFIG -jar $HOME_DIR/OleCheck.jar $1
